version: '3.1'
services:
    nginx:
        image: nginx:latest
        container_name: nginx
        depends_on:
            - flask
        volumes:
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
        networks:
            - my-network
        ports:
            - 80:80
    flask:
        build:
            context: ./
            dockerfile: Dockerfile
        image: lastofthedinosaursio:1.0.0
        container_name: flask
        volumes:
            - ./:/code/
        environment:
            - FLASK_APP=/lastofthedinosaursio/__init__.py
        command: flask run --host=0.0.0.0
        networks:
            my-network:
                aliases:
                    - flask-app
        ports:
            - 8080:5000

networks:
    my-network: